# Generated by Django 2.2.7 on 2019-11-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(db_index=True, max_length=2000, unique=True, verbose_name='Original URL')),
                ('short_url', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Short url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
